version: '3.4'

services:
  todos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80"

  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80:80"

  consul:
    ports:
    - "8500:8500"