version: '3.4'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: todosuser
      POSTGRES_PASSWORD: todosuserpass
      POSTGRES_DB: todos
    ports:
      - "5432:5432"
    networks:
      - backend_network
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - backend_network

  todos:
    image: todos:latest
    build:
      context: .
      dockerfile: Src/Services/TodosService/Dockerfile
    container_name: todos
    depends_on:
      - consul
    networks:
      - backend_network

  api.gateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: Src/Gateways/API.Gateway/Dockerfile
    container_name: apigateway
    networks:
      - backend_network

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    networks:
      - backend_network
    
networks:
    backend_network: